tm-1036-clean-ad-computers-pipeline-tues2

diff --git a/.github/workflows/ad_clean_computers.yml b/.github/workflows/ad_clean_computers.yml
--- a/.github/workflows/ad_clean_computers.yml
+++ b/.github/workflows/ad_clean_computers.yml
@@ -274,7 +274,24 @@
               --output text \
               --comment "run-ad-verify-computers-pwsh"
 
-            aws s3 cp "s3://$S3_BUCKET/adcompscript/all_logs.zip" all_logs.zip
+        - name: Upload all logs to the runner with retry
+          run: |
+            MAX_RETRIES=3
+            RETRY_DELAY=5
+            COUNT=0
+
+            until aws s3 cp "s3://$S3_BUCKET/adcompscript/all_logs.zip" all_logs.zip; do
+              EXIT_CODE=$?
+              COUNT=$((COUNT + 1))
+              if [ $COUNT -ge $MAX_RETRIES ]; then
+                echo "Upload failed after $COUNT attempts."
+                exit $EXIT_CODE
+              fi
+              echo "Upload failed. Retrying in $RETRY_DELAY seconds... (Attempt $COUNT of $MAX_RETRIES)"
+              sleep $RETRY_DELAY
+            done
+  
+            #aws s3 cp "s3://$S3_BUCKET/adcompscript/all_logs.zip" all_logs.zip
 
         - name: Upload all results
           uses: actions/upload-artifact@v4
