PLAT-190: offloc pipeline fixes (#274)
* ndh offloc pipeline: Add days option

* -

* -

* -

* -

* -

* -

diff --git a/.github/workflows/ndh_offloc_cloudplatfom_copy.yml b/.github/workflows/ndh_offloc_cloudplatfom_copy.yml
--- a/.github/workflows/ndh_offloc_cloudplatfom_copy.yml
+++ b/.github/workflows/ndh_offloc_cloudplatfom_copy.yml
@@ -4,10 +4,10 @@ name: NDH Offloc Copy to Cloud Platform
 on:
   workflow_dispatch:
     inputs:
-      check_files:
+      dryrun:
         type: choice
-        description: Check files mode (show what files exist in each bucket without transferring)
-        default: "false" # Change to true to enable check files mode
+        description: Dryrun mode. Leave as false unless testing pipeline
+        default: "false"
         options:
           - "true"
           - "false"
@@ -18,6 +18,10 @@ on:
         options:
           - "preprod"
           - "prod"
+      days_ago:
+        type: number
+        description: Set to 0 to copy the latest file, 1 to copy yesterday's file etc
+        default: 0
 
   schedule:
     - cron: "00 23 * * *"
@@ -33,7 +37,7 @@ permissions:
   id-token: write
   contents: read
 
-run-name: ${{ github.event_name == 'schedule' && 'NDH Offloc Copy to Cloud Platform prod' || format('NDH Offloc Copy to Cloud Platform {0}{1}', inputs.cp_environment, inputs.check_files == 'true' && ' (check files)' || '') }}
+run-name: ${{ github.event_name == 'schedule' && 'NDH Offloc Copy to Cloud Platform prod' || format('NDH Offloc Copy to Cloud Platform {0}{1}', inputs.cp_environment, inputs.dryrun == 'true' && ' (dryrun)' || '') }}
 
 
 jobs:
@@ -41,9 +45,9 @@ jobs:
     name: Setup
     runs-on: ubuntu-latest
     outputs:
-        check_files: "${{ steps.parseinput.outputs.check_files }}"
+        dryrun: "${{ steps.parseinput.outputs.dryrun }}"
         cp_environment: "${{ steps.parseinput.outputs.cp_environment }}"
-        today: "${{ steps.parseinput.outputs.today }}"
+        day: "${{ steps.parseinput.outputs.day }}"
         file_name: "${{ steps.parseinput.outputs.file_name }}"
         current_time: "${{ steps.parseinput.outputs.current_time }}"
     steps:
@@ -57,52 +61,45 @@ jobs:
         run: |
             # Check trigger types and set values
             if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
-              check_files="${{ github.event.inputs.check_files }}"
+              dryrun="${{ github.event.inputs.dryrun }}"
               cp_environment="${{ github.event.inputs.cp_environment }}"
+              days_ago="${{ github.event.inputs.days_ago }}"
               echo "Manual trigger detected - using provided inputs"
             elif [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
-              check_files="false"
+              dryrun="false"
               cp_environment="prod"
-              echo "Scheduled trigger detected - using production environment and set check_files to false "
+              days_ago=0
             else
               echo "Unsupported event ${GITHUB_EVENT_NAME}"
               exit 1
             fi
 
-            echo "check_files=${check_files}" >> $GITHUB_OUTPUT
+            echo "dryrun=${dryrun}" >> $GITHUB_OUTPUT
             echo "cp_environment=${cp_environment}" >> $GITHUB_OUTPUT
 
             # Generate date and file variables
-            TODAY=$(TZ="Europe/London" date +"%d%m%Y")
-            SOURCE_OFFLOC_FILE_DATE=$(TZ="Europe/London" date -d "yesterday" +"%d%m%Y")
+            DAY=$(TZ="Europe/London" date -d "$days_ago days ago" +"%Y%m%d")
+            SOURCE_OFFLOC_FILE_DATE=$(TZ="Europe/London" date -d "$((days_ago + 1)) days ago" +"%d%m%Y")
             FILE_NAME="C_NOMIS_OFFENDER_${SOURCE_OFFLOC_FILE_DATE}_01.dat"
             CURRENT_TIME=$(TZ="Europe/London" date)
 
-            echo "today=${TODAY}" >> $GITHUB_OUTPUT
+            echo "day=${DAY}" >> $GITHUB_OUTPUT
             echo "source_offloc_file_date=${SOURCE_OFFLOC_FILE_DATE}" >> $GITHUB_OUTPUT
             echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT
             echo "current_time=${CURRENT_TIME}" >> $GITHUB_OUTPUT
 
             echo "Setup complete:"
-            echo "- Check files mode: ${check_files}"
-            echo "- Today: ${TODAY}"
+            echo "- Dryrun: ${dryrun}"
+            echo "- CP Environment: ${cp_environment}"
+            echo "- Target Day: ${DAY}"
             echo "- Source Offloc file date: ${SOURCE_OFFLOC_FILE_DATE}"
-            echo "- Target Offloc file name: ${FILE_NAME}"
+            echo "- Source Offloc file name: ${FILE_NAME}"
             echo "- Pipeline run time: ${CURRENT_TIME}"
-
-            if [[ "${check_files}" == "true" ]]; then
-              echo "Running in check files mode."
-            else
-              echo "Running in transfer mode."
-            fi
 
   copytocloudplatform:
     name: Copy to Cloud Platform
     needs: setup
     runs-on: ubuntu-latest
-    outputs:
-      source_file_exists: ${{ steps.check_source.outputs.source_file_exists }}
-      dest_file_exists: ${{ steps.check_dest.outputs.dest_file_exists }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
@@ -128,7 +125,7 @@ jobs:
         env:
             SOURCE_BUCKET: ${{ secrets.OFFLOC_SOURCE_BUCKET }}
             FILE_NAME: ${{ needs.setup.outputs.file_name }}
-            TODAY: ${{ needs.setup.outputs.today }}
+            DAY: ${{ needs.setup.outputs.day }}
             CURRENT_TIME: ${{ needs.setup.outputs.current_time }}
         run: |
             echo "Checking source bucket for: ${FILE_NAME}"
@@ -136,10 +133,8 @@ jobs:
             # Check if the target file exists in source bucket
             if aws s3 ls "s3://${SOURCE_BUCKET}/${FILE_NAME}" >/dev/null 2>&1; then
               echo "File ${FILE_NAME} found in source bucket"
-              echo "source_file_exists=true" >> $GITHUB_OUTPUT
             else
-              echo "File for ${TODAY} is not yet available at ${CURRENT_TIME}"
-              echo "source_file_exists=false" >> $GITHUB_OUTPUT
+              echo "File for ${DAY} is not yet available at ${CURRENT_TIME}"
 
               # Find the most recent file in source bucket
               echo "Looking for most recent file in source bucket..."
@@ -155,14 +150,15 @@ jobs:
               else
                 echo "C_NOMIS_OFFENDER files not found in source bucket"
               fi
+              exit 1
             fi
 
       - name: Download File
         id: download_file
-        if: needs.setup.outputs.check_files == 'false' && steps.check_source.outputs.source_file_exists == 'true'
         env:
             SOURCE_BUCKET: ${{ secrets.OFFLOC_SOURCE_BUCKET }}
             FILE_NAME: ${{ needs.setup.outputs.file_name }}
+            DAY: ${{ needs.setup.outputs.day }}
         run: |
             LOCAL_FILE="/tmp/${FILE_NAME}"
 
@@ -171,7 +167,6 @@ jobs:
 
             if [[ $? -eq 0 ]]; then
               echo "File downloaded successfully to ${LOCAL_FILE}"
-              echo "file_downloaded=true" >> $GITHUB_OUTPUT
               echo "local_file=${LOCAL_FILE}" >> $GITHUB_OUTPUT
             else
               echo "Failed to download file"
@@ -180,11 +175,11 @@ jobs:
 
       - name: Prepare File for Upload
         id: prepare_file
-        if: needs.setup.outputs.check_files == 'false' && steps.download_file.outputs.file_downloaded == 'true'
+        env:
+            DAY: ${{ needs.setup.outputs.day }}
         run: |
             LOCAL_FILE="${{ steps.download_file.outputs.local_file }}"
-            TODAY_YYYYMMDD=$(TZ="Europe/London" date +"%Y%m%d")
-            ZIP_FILE="/tmp/${TODAY_YYYYMMDD}.zip"
+            ZIP_FILE="/tmp/${DAY}.zip"
 
             echo "Creating zip file: ${ZIP_FILE}"
             zip -j "${ZIP_FILE}" "${LOCAL_FILE}"
@@ -192,7 +187,7 @@ jobs:
             if [[ $? -eq 0 ]]; then
               echo "File zipped successfully to ${ZIP_FILE}"
               echo "zip_file=${ZIP_FILE}" >> $GITHUB_OUTPUT
-              echo "zip_filename=${TODAY_YYYYMMDD}.zip" >> $GITHUB_OUTPUT
+              echo "zip_filename=${DAY}.zip" >> $GITHUB_OUTPUT
 
               # Clean up original file
               rm -f "${LOCAL_FILE}"
@@ -213,7 +208,6 @@ jobs:
         id: check_dest
         env:
           DEST_BUCKET: ${{ needs.setup.outputs.cp_environment == 'preprod' && secrets.OFFLOC_TRANSFER_S3_BUCKET_NAME_PREPROD || secrets.OFFLOC_TRANSFER_S3_BUCKET_NAME_PROD }}
-          TODAY: ${{ needs.setup.outputs.today }}
           CURRENT_TIME: ${{ needs.setup.outputs.current_time }}
           CHECK_FILES: ${{ needs.setup.outputs.check_files }}
         run: |
@@ -221,8 +215,8 @@ jobs:
           if [[ "${{ steps.prepare_file.outputs.zip_filename }}" != "" ]]; then
             ZIP_FILENAME="${{ steps.prepare_file.outputs.zip_filename }}"
           else
-            TODAY_YYYYMMDD=$(TZ="Europe/London" date +"%Y%m%d")
-            ZIP_FILENAME="${TODAY_YYYYMMDD}.zip"
+            echo "Missing zip filename from previous step"
+            exit 1
           fi
 
           echo "Checking destination bucket for: ${ZIP_FILENAME}"
@@ -252,33 +246,37 @@ jobs:
           fi
 
       - name: Process File Transfer
-        if: needs.setup.outputs.check_files == 'false' && steps.check_source.outputs.source_file_exists == 'true'
         env:
           DEST_BUCKET: ${{ needs.setup.outputs.cp_environment == 'preprod' && secrets.OFFLOC_TRANSFER_S3_BUCKET_NAME_PREPROD || secrets.OFFLOC_TRANSFER_S3_BUCKET_NAME_PROD }}
-          TODAY: ${{ needs.setup.outputs.today }}
+          DAY: ${{ needs.setup.outputs.day }}
           CURRENT_TIME: ${{ needs.setup.outputs.current_time }}
         run: |
+          DRYRUN=${{ needs.setup.outputs.dryrun }}
           ZIP_FILE="${{ steps.prepare_file.outputs.zip_file }}"
           ZIP_FILENAME="${{ steps.prepare_file.outputs.zip_filename }}"
 
           if [[ "${{ steps.check_dest.outputs.dest_file_exists }}" == "true" ]]; then
-            echo "File for ${TODAY} already available at ${CURRENT_TIME}"
+            echo "File for ${DAY} already available at ${CURRENT_TIME}"
             echo "Deleting zip file..."
             rm -f "${ZIP_FILE}"
             echo "Zip file deleted"
           else
             echo "Uploading ${ZIP_FILENAME} to destination bucket..."
-            aws s3 cp "${ZIP_FILE}" "s3://${DEST_BUCKET}/${ZIP_FILENAME}"  # Use full path for source, filename for destination
+            if [[ $DRYRUN == "false" ]]; then
+              aws s3 cp "${ZIP_FILE}" "s3://${DEST_BUCKET}/${ZIP_FILENAME}"  # Use full path for source, filename for destination
 
-            if [[ $? -eq 0 ]]; then
-              echo "File ${ZIP_FILENAME} uploaded, local file deleted at ${CURRENT_TIME}"
-              rm -f "${ZIP_FILE}"
-              echo "Zip file deleted"
+              if [[ $? -eq 0 ]]; then
+                echo "File ${ZIP_FILENAME} uploaded, local file deleted at ${CURRENT_TIME}"
+                rm -f "${ZIP_FILE}"
+                echo "Zip file deleted"
+              else
+                echo "Failed to upload file"
+                rm -f "${ZIP_FILE}"
+                echo "Zip file deleted after failed upload"
+                exit 1
+              fi
             else
-              echo "Failed to upload file"
-              rm -f "${ZIP_FILE}"
-              echo "Zip file deleted after failed upload"
-              exit 1
+              echo "DRYRUN: aws s3 cp '${ZIP_FILE}' 's3://${DEST_BUCKET}/${ZIP_FILENAME}'"  # Use full path for source, filename for destination
             fi
           fi
 
@@ -289,7 +287,6 @@ jobs:
           echo "- Environment: ${{ needs.setup.outputs.cp_environment }}"
           echo "- Source file: ${{ needs.setup.outputs.file_name }}"
           echo "- Target zip file: ${{ steps.prepare_file.outputs.zip_filename || 'Not created' }}"
-          echo "- Source file exists: ${{ steps.check_source.outputs.source_file_exists || 'unknown' }}"
           echo "- Destination file exists: ${{ steps.check_dest.outputs.dest_file_exists || 'unknown' }}"
           echo "- Pipeline run time: ${{ needs.setup.outputs.current_time }}"
 
