.

diff --git a/.github/workflows/oasys_database_refresh.yml b/.github/workflows/oasys_database_refresh.yml
--- a/.github/workflows/oasys_database_refresh.yml
+++ b/.github/workflows/oasys_database_refresh.yml
@@ -40,46 +40,46 @@ jobs:
     steps:
       - name: Parse Inputs
         run: |
-        if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
-          source_db_name:  "${{github.event.inputs.source_db_name}}"
-          target_db_hostname: "${{github.event.inputs.target_db_hostname}}"
-          target_db_name: "${{github.event.inputs.target_db_name}}"
-          echo "Restoring ${source_database} database on ${target_host}"
-          if [[ -z "${target_db_hostname }" || -z "${source_db_name}"  || -z "{target_db_name}"]]; then
-            echo "Error, target host name, source database and target database name must all be specified"
-            exit 1
-          fi
-          if ! (echo "${ALLOWED_PARAMS}" | grep -w "${target_db_hostname}:${source_db_name}:${target_db_name}" > /dev/null); then
-            echo "Unsupported target_db_hostname / source_db_name / target_db_name combination"
-            echo "[${target_db_hostname}:${source_db_name}:${target_db_name}] not in [${ALLOWED_PARAMS}]"
-            exit 1
-          fi
-        elif  [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
-          cron_time="${{github.event.schedule}}"
-          if [[ "${cron_time}" == '00 07 * * 0' ]]; then
-            target_db_hostname="pp-oasys-db-a"
-            source_db_name="OASPROD"
-            target_db_name="PPOASYS"
-          elif [[ "${cron_time}" == '00 08 * * 0' ]]; then
-            target_db_hostname="pp-onr-db-a"
-            source_db_name="OASREP"
-            target_db_name="PPOASREP"
-          elif [[ "${cron_time}" == '00 09 * * 0' ]]; then
-            target_db_hostname="pp-onr-db-a"
-            source_db_name="OASREP"
-            target_db_name="PPOASRP2"
-          elif [[ "${cron_time}" == '00 10 * * 0' ]]; then
-            target_db_hostname="pp-onr-db-a"
-            source_db_name="MISTRANS"
-            target_db_name="PPMISTRN"
-          elif [[ "${cron_time}" == '00 11 * * 0' ]]; then
-            target_db_hostname="pp-onr-db-a"
-            source_db_name="MISTRANS"
-            target_db_name="PPMISTRN2"
-          else
-            echo "Github Event ${GITHUB_EVENT_NAME} unsupported"
-            exit 1
-          fi
+          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
+            source_db_name:  "${{github.event.inputs.source_db_name}}"
+            target_db_hostname: "${{github.event.inputs.target_db_hostname}}"
+            target_db_name: "${{github.event.inputs.target_db_name}}"
+            echo "Restoring ${source_database} database on ${target_host}"
+            if [[ -z "${target_db_hostname }" || -z "${source_db_name}"  || -z "{target_db_name}"]]; then
+              echo "Error, target host name, source database and target database name must all be specified"
+              exit 1
+            fi
+            if ! (echo "${ALLOWED_PARAMS}" | grep -w "${target_db_hostname}:${source_db_name}:${target_db_name}" > /dev/null); then
+              echo "Unsupported target_db_hostname / source_db_name / target_db_name combination"
+              echo "[${target_db_hostname}:${source_db_name}:${target_db_name}] not in [${ALLOWED_PARAMS}]"
+              exit 1
+            fi
+          elif  [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
+            cron_time="${{github.event.schedule}}"
+            if [[ "${cron_time}" == '00 07 * * 0' ]]; then
+              target_db_hostname="pp-oasys-db-a"
+              source_db_name="OASPROD"
+              target_db_name="PPOASYS"
+            elif [[ "${cron_time}" == '00 08 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="OASREP"
+              target_db_name="PPOASREP"
+            elif [[ "${cron_time}" == '00 09 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="OASREP"
+              target_db_name="PPOASRP2"
+            elif [[ "${cron_time}" == '00 10 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="MISTRANS"
+              target_db_name="PPMISTRN"
+            elif [[ "${cron_time}" == '00 11 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="MISTRANS"
+              target_db_name="PPMISTRN2"
+            else
+              echo "Github Event ${GITHUB_EVENT_NAME} unsupported"
+              exit 1
+            fi
 
   refresh_db:
     uses: ./.github/workflows/database_refresh.yml
