Oasys db refresh (#55)
* Updated to add branch for modernisation-platform-configuration-management

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* .

* Updated to add test schedule for PP-OASYS-DB-B

* Update oasys_database_refresh.yml

Signed-off-by: Sandhya1874 <39799075+Sandhya1874@users.noreply.github.com>

* Update oasys_database_refresh.yml

Signed-off-by: Sandhya1874 <39799075+Sandhya1874@users.noreply.github.com>

* Update oasys_database_refresh.yml

Signed-off-by: Sandhya1874 <39799075+Sandhya1874@users.noreply.github.com>

---------

Signed-off-by: Sandhya1874 <39799075+Sandhya1874@users.noreply.github.com>

diff --git a/.github/workflows/oasys_database_refresh.yml b/.github/workflows/oasys_database_refresh.yml
--- a/.github/workflows/oasys_database_refresh.yml
+++ b/.github/workflows/oasys_database_refresh.yml
@@ -21,16 +21,81 @@ on:
         required: true
         type: string
 
+  # Each scheduled job requires a unique time
+  schedule:
+    - cron: '00 07 * * 0' # pp-oasys-db-a PPOASYS
+    - cron: '00 08 * * 0' # pp-onr-db-a PPOASREP
+    - cron: '00 09 * * 0' # pp-onr-db-a PPOASRP2
+    - cron: '00 10 * * 0' # pp-onr-db-a PPMISTRN
+    - cron: '00 11 * * 0' # pp-onr-db-a PPMISTN2
+    - cron: '00 14 * * *' # pp-onr-db-b PPOASYS
+
+env:
+  ALLOWED_PARAMS: "pp-oasys-db-a:OASPROD:PPOASYS pp-onr-db-a:MISTRANS:PPMISTRN pp-onr-db-a:MISTRANS:PPMISTN2 pp-onr-db-a:OASREP:PPOASREP pp-onr-db-a:OASREP:PPOASRP2 pp-oasys-db-b:OASPROD:PPOASYS"
+
 jobs:
+  parse_input:
+    name: Parse input
+    runs-on: ubuntu-latest
+    steps:
+      - name: Parse Inputs
+        run: |
+          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
+            source_db_name="${{github.event.inputs.source_db_name}}"
+            target_db_hostname="${{github.event.inputs.target_db_hostname}}"
+            target_db_name="${{github.event.inputs.target_db_name}}"
+            echo "Restoring ${target_db_name} database on ${target_db_hostname}"
+            if [[ -z "${target_db_hostname}" || -z "${source_db_name}"  || -z "{target_db_name}" ]]; then
+              echo "Error, target host name, source database and target database name must all be specified"
+              exit 1
+            fi
+            if ! (echo "${ALLOWED_PARAMS}" | grep -w "${target_db_hostname}:${source_db_name}:${target_db_name}" > /dev/null); then
+              echo "Unsupported target_db_hostname / source_db_name / target_db_name combination"
+              echo "[${target_db_hostname}:${source_db_name}:${target_db_name}] not in [${ALLOWED_PARAMS}]"
+              exit 1
+            fi
+          elif  [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
+            cron_time="${{github.event.schedule}}"
+            if [[ "${cron_time}" == '00 07 * * 0' ]]; then
+              target_db_hostname="pp-oasys-db-a"
+              source_db_name="OASPROD"
+              target_db_name="PPOASYS"
+            elif [[ "${cron_time}" == '00 08 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="OASREP"
+              target_db_name="PPOASREP"
+            elif [[ "${cron_time}" == '00 09 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="OASREP"
+              target_db_name="PPOASRP2"
+            elif [[ "${cron_time}" == '00 10 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="MISTRANS"
+              target_db_name="PPMISTRN"
+            elif [[ "${cron_time}" == '00 11 * * 0' ]]; then
+              target_db_hostname="pp-onr-db-a"
+              source_db_name="MISTRANS"
+              target_db_name="PPMISTRN2"
+            elif [[ "${cron_time}" == '00 14 * * *' ]]; then
+              target_db_hostname="pp-oasys-db-b"
+              source_db_name="OASPROD"
+              target_db_name="PPOASYS"
+            else
+              echo "Github Event ${GITHUB_EVENT_NAME} unsupported"
+              exit 1
+            fi
+          fi
+
   refresh_db:
+    needs: parse_input
     uses: ./.github/workflows/database_refresh.yml
     with:
       source_oem_account_name: "hmpps-oem-production"
       source_oem_hostname: "prod-oem-a"
-      source_db_name:  "${{github.event.inputs.source_db_name}}"
+      source_db_name:  "${source_db_name}"
       target_db_account_name: "oasys-preproduction"
-      target_db_hostname: "${{github.event.inputs.target_db_hostname}}"
-      target_db_name: "${{github.event.inputs.target_db_name}}"
+      target_db_hostname: "${target_db_hostname}"
+      target_db_name: "${target_db_name}"
     secrets:
       environment_management: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT }}
       dso_github_pat: ${{ secrets.DSO_GITHUB_PAT }}
