test

diff --git a/.github/workflows/ssm_command_monitoring.yml b/.github/workflows/ssm_command_monitoring.yml
--- a/.github/workflows/ssm_command_monitoring.yml
+++ b/.github/workflows/ssm_command_monitoring.yml
@@ -1,15 +1,24 @@
----
-name: SSM Command Monitoring
+name: GitHub Workflow Monitoring
+
+permissions:
+  id-token: write
+  contents: read
 
 on:
   workflow_dispatch:
     inputs:
+      repos:
+        description: 'e.g. all'
+        type: string
+        default: all
       applications:
-        description: 'e.g. nomis or leave blank for all'
+        description: 'e.g. hmpps-oem'
         type: string
+        default: hmpps-oem
       environments:
-        description: 'e.g. development or leave blank for all'
+        description: 'e.g. test'
         type: string
+        default: test
       interval:
         description: 'time interval to check in seconds, default 6 hours'
         type: number
@@ -31,16 +40,13 @@ on:
   schedule:
     - cron: "0 * * * *"
 
-permissions:
-  id-token: write
-  contents: read
-
 jobs:
   check-strategy:
     name: Check Strategy
     runs-on: ubuntu-latest
     outputs:
       matrix: "${{ steps.strategy.outputs.matrix }}"
+      repos: "${{ steps.strategy.outputs.repos }}"
       interval: "${{ steps.options.outputs.interval }}"
       round: "${{ steps.options.outputs.round }}"
       dryrun: "${{ steps.options.outputs.dryrun }}"
@@ -73,14 +79,16 @@ jobs:
       - name: Options
         id: options
         run: |
+          echo "Setting options event=${GITHUB_EVENT_NAME}"
           dryrun=false
           round=false
           interval=21600
-          echo "Setting options event=${GITHUB_EVENT_NAME}"
+          repos=all
           if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
             dryrun="${{ github.event.inputs.dryrun }}"
             round="${{ github.event.inputs.round }}"
             interval="${{ github.event.inputs.interval }}"
+            repos="${{ github.event.inputs.repos }}"
           elif [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
             interval=3600
             round=true
@@ -88,13 +96,14 @@ jobs:
             echo "Unsupported event ${GITHUB_EVENT_NAME}"
             exit 1
           fi
-          echo "dryrun=${dryrun} interval=${interval} round=${round}"
+          echo "dryrun=${dryrun} interval=${interval} round=${round} repos=${repos}"
           echo "dryrun=${dryrun}" >> $GITHUB_OUTPUT
           echo "interval=${interval}" >> $GITHUB_OUTPUT
           echo "round=${round}" >> $GITHUB_OUTPUT
+          echo "repos=${repos}" >> $GITHUB_OUTPUT
 
-  check-ssm:
-    name: Check SSM
+  check-github:
+    name: Check GHA Runs
     runs-on: ubuntu-latest
     needs: check-strategy
     strategy:
@@ -122,28 +131,29 @@ jobs:
         with:
           ref: ${{ github.ref }}
 
-      - name: Monitor SSM Commands
+      - name: Monitor GitHub Workflow Runs
         id: monitor
         env:
           dryrun: ${{ needs.check-strategy.outputs.dryrun }}
           round: ${{ needs.check-strategy.outputs.round }}
           interval: ${{ needs.check-strategy.outputs.interval }}
+          repos: ${{ needs.check-strategy.outputs.repos }}
+          GITHUB_TOKEN: ${{ secrets.DSO_GITHUB_PAT }}
         run: |
-          options="-i $interval -c"
+          options="-i $interval -c -v"
           if [[ $dryrun == "true" ]]; then
             options="$options -d"
           fi
           if [[ $round == "true" ]]; then
             options="$options -r"
           fi
-          echo src/ssm-command-monitoring/ssm-command-monitor.sh $options
-          src/ssm-command-monitoring/ssm-command-monitor.sh $options 2>output.txt || exitcode=$?
+          exitcode=0
+          echo src/github-workflow-monitoring/github-workflow-monitor.sh $options $repos
+          src/github-workflow-monitoring/github-workflow-monitor.sh $options $repos 2>output.txt || exitcode=$?
           failedcount=$(cat output.txt | grep "^Verbose1: " | cut -d" " -f2- | wc -l | tr -d [[:space:]])
-          ignoredcount=$(cat output.txt | grep "^Verbose2: " | cut -d" " -f2- | wc -l | tr -d [[:space:]])
-          echo "exitcode=${exitcode} failedcount=${failedcount} ignoredcount=${ignoredcount}"
+          echo "exitcode=${exitcode} failedcount=${failedcount}"
           echo "exitcode=${exitcode}" >> $GITHUB_OUTPUT
           echo "failedcount=${failedcount}" >> $GITHUB_OUTPUT
-          echo "ignoredcount=${ignoredcount}" >> $GITHUB_OUTPUT
 
       - name: Dryrun SSM Commands
         if: ${{ needs.check-strategy.outputs.dryrun == 'true' }}
@@ -154,11 +164,6 @@ jobs:
         if: ${{ steps.monitor.outputs.failedcount != 0 }}
         run: |
           cat output.txt | grep "^Verbose1: " | cut -d" " -f2-
-
-      - name: Debug Ignored SSM Commands
-        if: ${{ steps.monitor.outputs.ignoredcount != 0 }}
-        run: |
-          cat output.txt | grep "^Verbose2: " | cut -d" " -f2-
 
       - name: Debug Error
         if: ${{ steps.monitor.outputs.exitcode != 0 }}
